version: '3.4'

networks:
  weather-bridge:
    driver: overlay
    attachable: true
    

volumes:
  cache:
    driver: local    

services:

  weather-example:
    # To use example image from repo
    image: ghcr.io/gaaaabor/gaaaabor.akka.discovery.docker/gaaaabor.akka.discovery.docker.dockerexample:docker_swarm_support
    # To use example from local code
    # build:
    #     context: .
    #     dockerfile: examples/DockerExample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - UseSwarm=True
    networks:
      - weather-bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.docker.compose.service=weather-example
    ports:
      - 0:80
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.architecture == amd

  weather-example-arm:
    # To use example image from repo
    image: ghcr.io/gaaaabor/gaaaabor.akka.discovery.docker/gaaaabor.akka.discovery.docker.dockerexample.arm:docker_swarm_support
    # To use example from local code
    # build:
    #     context: .
    #     dockerfile: examples/DockerExample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - UseSwarm=True
    networks:
      - weather-bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.docker.compose.service=weather-example
    ports:
      - 0:80
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.architecture == arm
      
